-- Mineral spawn probability data extracted from Star Citizen Game2.dcb (4.x)
CREATE TABLE IF NOT EXISTS mineral_spawns (
  id             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  system         TEXT NOT NULL,
  body           TEXT NOT NULL,
  body_type      TEXT NOT NULL,
  parent_body    TEXT,
  mineral        TEXT NOT NULL,
  mining_type    TEXT NOT NULL,
  spawn_prob_pct NUMERIC(6,2) NOT NULL,
  group_prob     NUMERIC(6,2),
  data_version   TEXT DEFAULT '4.x',
  source_file    TEXT
);

ALTER TABLE mineral_spawns ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read" ON mineral_spawns FOR SELECT USING (true);

GRANT SELECT ON mineral_spawns TO anon, authenticated;

INSERT INTO mineral_spawns (system, body, body_type, parent_body, mineral, mining_type, spawn_prob_pct, group_prob, data_version, source_file) VALUES
('Stanton', 'Aaron Halo', 'asteroid_belt', NULL, 'Aluminium', 'ship_asteroid', 10.3, 0.3, '4.x', 'hpp_aaronhalo'),
('Stanton', 'Aaron Halo', 'asteroid_belt', NULL, 'Aslarite', 'ship_asteroid', 14.2, 0.3, '4.x', 'hpp_aaronhalo'),
('Stanton', 'Aaron Halo', 'asteroid_belt', NULL, 'Beryl', 'ship_asteroid', 18.0, 0.3, '4.x', 'hpp_aaronhalo'),
('Stanton', 'Aaron Halo', 'asteroid_belt', NULL, 'Copper', 'ship_asteroid', 10.3, 0.3, '4.x', 'hpp_aaronhalo'),
('Stanton', 'Aaron Halo', 'asteroid_belt', NULL, 'Ice', 'ship_asteroid', 10.4, 0.3, '4.x', 'hpp_aaronhalo'),
('Stanton', 'Aaron Halo', 'asteroid_belt', NULL, 'Iron', 'ship_asteroid', 10.3, 0.3, '4.x', 'hpp_aaronhalo'),
('Stanton', 'Aaron Halo', 'asteroid_belt', NULL, 'Quantainium', 'ship_asteroid', 2.0, 0.3, '4.x', 'hpp_aaronhalo'),
('Stanton', 'Aaron Halo', 'asteroid_belt', NULL, 'Silicon', 'ship_asteroid', 10.3, 0.3, '4.x', 'hpp_aaronhalo'),
('Stanton', 'Aaron Halo', 'asteroid_belt', NULL, 'Titanium', 'ship_asteroid', 14.2, 0.3, '4.x', 'hpp_aaronhalo'),
('Stanton', 'Aberdeen', 'moon', 'Hurston', 'Aluminium', 'ship_asteroid', 29.7, 6.0, '4.x', 'hpp_stanton1b'),
('Stanton', 'Aberdeen', 'moon', 'Hurston', 'Aphorite', 'fps', 58.6, 25.0, '4.x', 'hpp_stanton1b'),
('Stanton', 'Aberdeen', 'moon', 'Hurston', 'Beradom', 'ground_vehicle', 4.0, 12.5, '4.x', 'hpp_stanton1b'),
('Stanton', 'Aberdeen', 'moon', 'Hurston', 'Corundum', 'ship_asteroid', 29.8, 6.0, '4.x', 'hpp_stanton1b'),
('Stanton', 'Aberdeen', 'moon', 'Hurston', 'Dolivine', 'fps', 35.4, 25.0, '4.x', 'hpp_stanton1b'),
('Stanton', 'Aberdeen', 'moon', 'Hurston', 'Feynmaline', 'ground_vehicle', 64.0, 12.5, '4.x', 'hpp_stanton1b'),
('Stanton', 'Aberdeen', 'moon', 'Hurston', 'Glacosite', 'ground_vehicle', 32.0, 12.5, '4.x', 'hpp_stanton1b'),
('Stanton', 'Aberdeen', 'moon', 'Hurston', 'Hadanite', 'fps', 6.0, 25.0, '4.x', 'hpp_stanton1b'),
('Stanton', 'Aberdeen', 'moon', 'Hurston', 'Ouratite', 'ship_asteroid', 10.0, 6.0, '4.x', 'hpp_stanton1b'),
('Stanton', 'Aberdeen', 'moon', 'Hurston', 'Quantainium', 'ship_asteroid', 2.0, 6.0, '4.x', 'hpp_stanton1b'),
('Stanton', 'Aberdeen', 'moon', 'Hurston', 'Titanium', 'ship_asteroid', 28.5, 6.0, '4.x', 'hpp_stanton1b'),
('Stanton', 'ArcCorp', 'planet', NULL, 'Aphorite', 'fps', 61.1, 25.0, '4.x', 'hpp_stanton3a'),
('Stanton', 'ArcCorp', 'planet', NULL, 'Beradom', 'ground_vehicle', 48.0, 12.5, '4.x', 'hpp_stanton3a'),
('Stanton', 'ArcCorp', 'planet', NULL, 'Copper', 'ship_asteroid', 34.77, 6.0, '4.x', 'hpp_stanton3a'),
('Stanton', 'ArcCorp', 'planet', NULL, 'Dolivine', 'fps', 36.9, 25.0, '4.x', 'hpp_stanton3a'),
('Stanton', 'ArcCorp', 'planet', NULL, 'Feynmaline', 'ground_vehicle', 4.0, 12.5, '4.x', 'hpp_stanton3a'),
('Stanton', 'ArcCorp', 'planet', NULL, 'Glacosite', 'ground_vehicle', 48.0, 12.5, '4.x', 'hpp_stanton3a'),
('Stanton', 'ArcCorp', 'planet', NULL, 'Iron', 'ship_asteroid', 34.77, 6.0, '4.x', 'hpp_stanton3a'),
('Stanton', 'ArcCorp', 'planet', NULL, 'Janalite', 'fps', 2.0, 25.0, '4.x', 'hpp_stanton3a'),
('Stanton', 'ArcCorp', 'planet', NULL, 'Laranite', 'ship_asteroid', 28.47, 6.0, '4.x', 'hpp_stanton3a'),
('Stanton', 'ArcCorp', 'planet', NULL, 'Quantainium', 'ship_asteroid', 2.0, 6.0, '4.x', 'hpp_stanton3a'),
('Stanton', 'Arial', 'moon', 'Hurston', 'Aluminium', 'ship_asteroid', 34.8, 6.0, '4.x', 'hpp_stanton1c'),
('Stanton', 'Arial', 'moon', 'Hurston', 'Aphorite', 'fps', 58.6, 25.0, '4.x', 'hpp_stanton1c'),
('Stanton', 'Arial', 'moon', 'Hurston', 'Aslarite', 'ship_asteroid', 14.2, 6.0, '4.x', 'hpp_stanton1c'),
('Stanton', 'Arial', 'moon', 'Hurston', 'Beradom', 'ground_vehicle', 3.7, 12.5, '4.x', 'hpp_stanton1c'),
('Stanton', 'Arial', 'moon', 'Hurston', 'Dolivine', 'fps', 35.4, 25.0, '4.x', 'hpp_stanton1c'),
('Stanton', 'Arial', 'moon', 'Hurston', 'Feynmaline', 'ground_vehicle', 37.04, 12.5, '4.x', 'hpp_stanton1c'),
('Stanton', 'Arial', 'moon', 'Hurston', 'Glacosite', 'ground_vehicle', 59.26, 12.5, '4.x', 'hpp_stanton1c'),
('Stanton', 'Arial', 'moon', 'Hurston', 'Hadanite', 'fps', 6.0, 25.0, '4.x', 'hpp_stanton1c'),
('Stanton', 'Arial', 'moon', 'Hurston', 'Iron', 'ship_asteroid', 34.8, 6.0, '4.x', 'hpp_stanton1c'),
('Stanton', 'Arial', 'moon', 'Hurston', 'Quantainium', 'ship_asteroid', 2.0, 6.0, '4.x', 'hpp_stanton1c'),
('Stanton', 'Arial', 'moon', 'Hurston', 'Titanium', 'ship_asteroid', 14.2, 6.0, '4.x', 'hpp_stanton1c'),
('Pyro', 'Bloom', 'planet', NULL, 'Aphorite', 'fps', 58.6, 12.5, '4.x', 'hpp_pyro4'),
('Pyro', 'Bloom', 'planet', NULL, 'Borase', 'ship_asteroid', 18.02, 7.5, '4.x', 'hpp_pyro4'),
('Pyro', 'Bloom', 'planet', NULL, 'Copper', 'ship_asteroid', 25.73, 7.5, '4.x', 'hpp_pyro4'),
('Pyro', 'Bloom', 'planet', NULL, 'Dolivine', 'fps', 35.4, 12.5, '4.x', 'hpp_pyro4'),
('Pyro', 'Bloom', 'planet', NULL, 'Feynmaline', 'ground_vehicle', 100.0, 25.0, '4.x', 'hpp_pyro4'),
('Pyro', 'Bloom', 'planet', NULL, 'Hadanite', 'fps', 6.0, 12.5, '4.x', 'hpp_pyro4'),
('Pyro', 'Bloom', 'planet', NULL, 'Iron', 'ship_asteroid', 25.73, 7.5, '4.x', 'hpp_pyro4'),
('Pyro', 'Bloom', 'planet', NULL, 'Laranite', 'ship_asteroid', 28.53, 7.5, '4.x', 'hpp_pyro4'),
('Pyro', 'Bloom', 'planet', NULL, 'Stileron', 'ship_asteroid', 2.0, 7.5, '4.x', 'hpp_pyro4'),
('Stanton', 'Calliope', 'moon', 'MicroTech', 'Aphorite', 'fps', 61.1, 25.0, '4.x', 'hpp_stanton4b'),
('Stanton', 'Calliope', 'moon', 'MicroTech', 'Beradom', 'ground_vehicle', 20.0, 12.5, '4.x', 'hpp_stanton4b'),
('Stanton', 'Calliope', 'moon', 'MicroTech', 'Copper', 'ship_asteroid', 40.0, 6.0, '4.x', 'hpp_stanton4b'),
('Stanton', 'Calliope', 'moon', 'MicroTech', 'Dolivine', 'fps', 36.9, 25.0, '4.x', 'hpp_stanton4b'),
('Stanton', 'Calliope', 'moon', 'MicroTech', 'Feynmaline', 'ground_vehicle', 12.0, 12.5, '4.x', 'hpp_stanton4b'),
('Stanton', 'Calliope', 'moon', 'MicroTech', 'Glacosite', 'ground_vehicle', 68.0, 12.5, '4.x', 'hpp_stanton4b'),
('Stanton', 'Calliope', 'moon', 'MicroTech', 'Ice', 'ship_asteroid', 40.0, 6.0, '4.x', 'hpp_stanton4b'),
('Stanton', 'Calliope', 'moon', 'MicroTech', 'Janalite', 'fps', 2.0, 25.0, '4.x', 'hpp_stanton4b'),
('Stanton', 'Calliope', 'moon', 'MicroTech', 'Quantainium', 'ship_asteroid', 2.0, 6.0, '4.x', 'hpp_stanton4b'),
('Stanton', 'Calliope', 'moon', 'MicroTech', 'Taranite', 'ship_asteroid', 18.0, 6.0, '4.x', 'hpp_stanton4b'),
('Stanton', 'Clio', 'moon', 'MicroTech', 'Aphorite', 'fps', 61.1, 25.0, '4.x', 'hpp_stanton4c'),
('Stanton', 'Clio', 'moon', 'MicroTech', 'Beradom', 'ground_vehicle', 12.0, 12.5, '4.x', 'hpp_stanton4c'),
('Stanton', 'Clio', 'moon', 'MicroTech', 'Copper', 'ship_asteroid', 40.0, 6.0, '4.x', 'hpp_stanton4c'),
('Stanton', 'Clio', 'moon', 'MicroTech', 'Dolivine', 'fps', 36.9, 25.0, '4.x', 'hpp_stanton4c'),
('Stanton', 'Clio', 'moon', 'MicroTech', 'Feynmaline', 'ground_vehicle', 0.0, 12.5, '4.x', 'hpp_stanton4c'),
('Stanton', 'Clio', 'moon', 'MicroTech', 'Glacosite', 'ground_vehicle', 88.0, 12.5, '4.x', 'hpp_stanton4c'),
('Stanton', 'Clio', 'moon', 'MicroTech', 'Ice', 'ship_asteroid', 40.0, 6.0, '4.x', 'hpp_stanton4c'),
('Stanton', 'Clio', 'moon', 'MicroTech', 'Janalite', 'fps', 2.0, 25.0, '4.x', 'hpp_stanton4c'),
('Stanton', 'Clio', 'moon', 'MicroTech', 'Quantainium', 'ship_asteroid', 2.0, 6.0, '4.x', 'hpp_stanton4c'),
('Stanton', 'Clio', 'moon', 'MicroTech', 'Taranite', 'ship_asteroid', 18.0, 6.0, '4.x', 'hpp_stanton4c'),
('Stanton', 'Crusader', 'planet', NULL, 'Agricium', 'ship_asteroid', 28.5, 6.0, '4.x', 'hpp_stanton2a'),
('Stanton', 'Crusader', 'planet', NULL, 'Aphorite', 'fps', 58.6, 25.0, '4.x', 'hpp_stanton2a'),
('Stanton', 'Crusader', 'planet', NULL, 'Beradom', 'ground_vehicle', 56.0, 12.5, '4.x', 'hpp_stanton2a'),
('Stanton', 'Crusader', 'planet', NULL, 'Dolivine', 'fps', 35.4, 25.0, '4.x', 'hpp_stanton2a'),
('Stanton', 'Crusader', 'planet', NULL, 'Feynmaline', 'ground_vehicle', 12.0, 12.5, '4.x', 'hpp_stanton2a'),
('Stanton', 'Crusader', 'planet', NULL, 'Glacosite', 'ground_vehicle', 32.0, 12.5, '4.x', 'hpp_stanton2a'),
('Stanton', 'Crusader', 'planet', NULL, 'Hadanite', 'fps', 6.0, 25.0, '4.x', 'hpp_stanton2a'),
('Stanton', 'Crusader', 'planet', NULL, 'Quantainium', 'ship_asteroid', 2.0, 6.0, '4.x', 'hpp_stanton2a'),
('Stanton', 'Crusader', 'planet', NULL, 'Quartz', 'ship_asteroid', 25.7, 6.0, '4.x', 'hpp_stanton2a'),
('Stanton', 'Crusader', 'planet', NULL, 'Silicon', 'ship_asteroid', 25.8, 6.0, '4.x', 'hpp_stanton2a'),
('Stanton', 'Crusader', 'planet', NULL, 'Taranite', 'ship_asteroid', 18.0, 6.0, '4.x', 'hpp_stanton2a'),
('Stanton', 'Daymar', 'moon', 'Crusader', 'Agricium', 'ship_asteroid', 28.5, 6.0, '4.x', 'hpp_stanton2b'),
('Stanton', 'Daymar', 'moon', 'Crusader', 'Aphorite', 'fps', 58.6, 25.0, '4.x', 'hpp_stanton2b'),
('Stanton', 'Daymar', 'moon', 'Crusader', 'Beradom', 'ground_vehicle', 48.0, 12.5, '4.x', 'hpp_stanton2b'),
('Stanton', 'Daymar', 'moon', 'Crusader', 'Dolivine', 'fps', 35.4, 25.0, '4.x', 'hpp_stanton2b'),
('Stanton', 'Daymar', 'moon', 'Crusader', 'Feynmaline', 'ground_vehicle', 40.0, 12.5, '4.x', 'hpp_stanton2b'),
('Stanton', 'Daymar', 'moon', 'Crusader', 'Glacosite', 'ground_vehicle', 12.0, 12.5, '4.x', 'hpp_stanton2b'),
('Stanton', 'Daymar', 'moon', 'Crusader', 'Hadanite', 'fps', 6.0, 25.0, '4.x', 'hpp_stanton2b'),
('Stanton', 'Daymar', 'moon', 'Crusader', 'Quantainium', 'ship_asteroid', 2.0, 6.0, '4.x', 'hpp_stanton2b'),
('Stanton', 'Daymar', 'moon', 'Crusader', 'Quartz', 'ship_asteroid', 34.7, 6.0, '4.x', 'hpp_stanton2b'),
('Stanton', 'Daymar', 'moon', 'Crusader', 'Silicon', 'ship_asteroid', 34.8, 6.0, '4.x', 'hpp_stanton2b'),
('Nyx', 'Glaciem Ring', 'asteroid_belt', NULL, 'Aluminium', 'ship_asteroid', 13.8, 0.1, '4.x', 'hpp_nyx_glaciemring'),
('Nyx', 'Glaciem Ring', 'asteroid_belt', NULL, 'Bexalite', 'ship_asteroid', 18.0, 0.1, '4.x', 'hpp_nyx_glaciemring'),
('Nyx', 'Glaciem Ring', 'asteroid_belt', NULL, 'Ice', 'ship_asteroid', 13.9, 0.1, '4.x', 'hpp_nyx_glaciemring'),
('Nyx', 'Glaciem Ring', 'asteroid_belt', NULL, 'Iron', 'ship_asteroid', 13.8, 0.1, '4.x', 'hpp_nyx_glaciemring'),
('Nyx', 'Glaciem Ring', 'asteroid_belt', NULL, 'Lindinium', 'ship_asteroid', 10.0, 0.1, '4.x', 'hpp_nyx_glaciemring'),
('Nyx', 'Glaciem Ring', 'asteroid_belt', NULL, 'Savrilium', 'ship_asteroid', 2.0, 0.1, '4.x', 'hpp_nyx_glaciemring'),
('Nyx', 'Glaciem Ring', 'asteroid_belt', NULL, 'Torite', 'ship_asteroid', 28.5, 0.1, '4.x', 'hpp_nyx_glaciemring'),
('Stanton', 'Hurston', 'planet', NULL, 'Aluminium', 'ship_asteroid', 44.0, 6.0, '4.x', 'hpp_stanton1, hpp_stanton1a'),
('Stanton', 'Hurston', 'planet', NULL, 'Aphorite', 'fps', 58.6, 25.0, '4.x', 'hpp_stanton1, hpp_stanton1a'),
('Stanton', 'Hurston', 'planet', NULL, 'Beradom', 'ground_vehicle', 64.0, 12.5, '4.x', 'hpp_stanton1, hpp_stanton1a'),
('Stanton', 'Hurston', 'planet', NULL, 'Corundum', 'ship_asteroid', 22.0, 6.0, '4.x', 'hpp_stanton1a'),
('Stanton', 'Hurston', 'planet', NULL, 'Dolivine', 'fps', 35.4, 25.0, '4.x', 'hpp_stanton1, hpp_stanton1a'),
('Stanton', 'Hurston', 'planet', NULL, 'Feynmaline', 'ground_vehicle', 4.0, 12.5, '4.x', 'hpp_stanton1, hpp_stanton1a'),
('Stanton', 'Hurston', 'planet', NULL, 'Glacosite', 'ground_vehicle', 32.0, 12.5, '4.x', 'hpp_stanton1, hpp_stanton1a'),
('Stanton', 'Hurston', 'planet', NULL, 'Gold', 'unknown', 17.07, 35.0, '4.x', 'hpp_stanton1'),
('Stanton', 'Hurston', 'planet', NULL, 'Hadanite', 'fps', 6.0, 25.0, '4.x', 'hpp_stanton1, hpp_stanton1a'),
('Stanton', 'Hurston', 'planet', NULL, 'Hephaestanite', 'ship_asteroid', 22.0, 6.0, '4.x', 'hpp_stanton1a'),
('Stanton', 'Hurston', 'planet', NULL, 'Ouratite', 'ship_asteroid', 10.0, 6.0, '4.x', 'hpp_stanton1, hpp_stanton1a'),
('Stanton', 'Hurston', 'planet', NULL, 'Quantainium', 'ship_asteroid', 2.0, 6.0, '4.x', 'hpp_stanton1, hpp_stanton1a'),
('Stanton', 'Hurston', 'planet', NULL, 'Tin', 'ship_asteroid', 44.0, 6.0, '4.x', 'hpp_stanton1, hpp_stanton1a'),
('Stanton', 'Ita', 'moon', 'Hurston', 'Aluminium', 'ship_asteroid', 34.7, 6.0, '4.x', 'hpp_stanton1d'),
('Stanton', 'Ita', 'moon', 'Hurston', 'Aphorite', 'fps', 58.6, 25.0, '4.x', 'hpp_stanton1d'),
('Stanton', 'Ita', 'moon', 'Hurston', 'Aslarite', 'ship_asteroid', 28.5, 6.0, '4.x', 'hpp_stanton1d'),
('Stanton', 'Ita', 'moon', 'Hurston', 'Beradom', 'ground_vehicle', 3.85, 12.5, '4.x', 'hpp_stanton1d'),
('Stanton', 'Ita', 'moon', 'Hurston', 'Dolivine', 'fps', 35.4, 25.0, '4.x', 'hpp_stanton1d'),
('Stanton', 'Ita', 'moon', 'Hurston', 'Feynmaline', 'ground_vehicle', 26.92, 12.5, '4.x', 'hpp_stanton1d'),
('Stanton', 'Ita', 'moon', 'Hurston', 'Glacosite', 'ground_vehicle', 69.23, 12.5, '4.x', 'hpp_stanton1d'),
('Stanton', 'Ita', 'moon', 'Hurston', 'Hadanite', 'fps', 6.0, 25.0, '4.x', 'hpp_stanton1d'),
('Stanton', 'Ita', 'moon', 'Hurston', 'Quantainium', 'ship_asteroid', 2.0, 6.0, '4.x', 'hpp_stanton1d'),
('Stanton', 'Ita', 'moon', 'Hurston', 'Tin', 'ship_asteroid', 34.8, 6.0, '4.x', 'hpp_stanton1d'),
('Nyx', 'Keeger Belt', 'asteroid_belt', NULL, 'Aluminium', 'ship_asteroid', 13.8, 0.1, '4.x', 'hpp_nyx_keegerbelt'),
('Nyx', 'Keeger Belt', 'asteroid_belt', NULL, 'Bexalite', 'ship_asteroid', 18.0, 0.1, '4.x', 'hpp_nyx_keegerbelt'),
('Nyx', 'Keeger Belt', 'asteroid_belt', NULL, 'Ice', 'ship_asteroid', 13.9, 0.1, '4.x', 'hpp_nyx_keegerbelt'),
('Nyx', 'Keeger Belt', 'asteroid_belt', NULL, 'Iron', 'ship_asteroid', 13.8, 0.1, '4.x', 'hpp_nyx_keegerbelt'),
('Nyx', 'Keeger Belt', 'asteroid_belt', NULL, 'Lindinium', 'ship_asteroid', 10.0, 0.1, '4.x', 'hpp_nyx_keegerbelt'),
('Nyx', 'Keeger Belt', 'asteroid_belt', NULL, 'Savrilium', 'ship_asteroid', 2.0, 0.1, '4.x', 'hpp_nyx_keegerbelt'),
('Nyx', 'Keeger Belt', 'asteroid_belt', NULL, 'Torite', 'ship_asteroid', 28.5, 0.1, '4.x', 'hpp_nyx_keegerbelt'),
('Stanton', 'L1 Lagrange', 'lagrange', NULL, 'Aluminium', 'ship_asteroid', 17.9, 0.1, '4.x', 'hpp_lagrange_a, hpp_lagrange_f'),
('Stanton', 'L1 Lagrange', 'lagrange', NULL, 'Borase', 'ship_asteroid', 18.0, 0.1, '4.x', 'hpp_lagrange_a'),
('Stanton', 'L1 Lagrange', 'lagrange', NULL, 'Corundum', 'ship_asteroid', 17.8, 0.1, '4.x', 'hpp_lagrange_a, hpp_lagrange_f'),
('Stanton', 'L1 Lagrange', 'lagrange', NULL, 'Hephaestanite', 'ship_asteroid', 17.8, 0.1, '4.x', 'hpp_lagrange_a, hpp_lagrange_f'),
('Stanton', 'L1 Lagrange', 'lagrange', NULL, 'Laranite', 'ship_asteroid', 28.5, 0.1, '4.x', 'hpp_lagrange_a'),
('Stanton', 'L1 Lagrange', 'lagrange', NULL, 'Taranite', 'ship_asteroid', 18.0, 0.15, '4.x', 'hpp_lagrange_f'),
('Stanton', 'L1 Lagrange', 'lagrange', NULL, 'Tungsten', 'ship_asteroid', 28.5, 0.15, '4.x', 'hpp_lagrange_f'),
('Stanton', 'L2 Lagrange', 'lagrange', NULL, 'Aslarite', 'ship_asteroid', 28.5, 0.15, '4.x', 'hpp_lagrange_b'),
('Stanton', 'L2 Lagrange', 'lagrange', NULL, 'Copper', 'ship_asteroid', 17.8, 0.15, '4.x', 'hpp_lagrange_b'),
('Stanton', 'L2 Lagrange', 'lagrange', NULL, 'Gold', 'ship_asteroid', 18.0, 0.15, '4.x', 'hpp_lagrange_b'),
('Stanton', 'L2 Lagrange', 'lagrange', NULL, 'Ice', 'ship_asteroid', 17.8, 0.15, '4.x', 'hpp_lagrange_b'),
('Stanton', 'L2 Lagrange', 'lagrange', NULL, 'Iron', 'ship_asteroid', 17.9, 0.15, '4.x', 'hpp_lagrange_b'),
('Stanton', 'L3 Lagrange', 'lagrange', NULL, 'Aluminium', 'ship_asteroid', 23.85, 0.075, '4.x', 'hpp_lagrange_c'),
('Stanton', 'L3 Lagrange', 'lagrange', NULL, 'Corundum', 'ship_asteroid', 23.85, 0.075, '4.x', 'hpp_lagrange_c'),
('Stanton', 'L3 Lagrange', 'lagrange', NULL, 'Hephaestanite', 'ship_asteroid', 23.85, 0.075, '4.x', 'hpp_lagrange_c'),
('Stanton', 'L3 Lagrange', 'lagrange', NULL, 'Torite', 'ship_asteroid', 28.44, 0.075, '4.x', 'hpp_lagrange_c'),
('Stanton', 'L4 Lagrange', 'lagrange', NULL, 'Agricium', 'ship_asteroid', 28.5, 0.1, '4.x', 'hpp_lagrange_d'),
('Stanton', 'L4 Lagrange', 'lagrange', NULL, 'Beryl', 'ship_asteroid', 18.0, 0.1, '4.x', 'hpp_lagrange_d'),
('Stanton', 'L4 Lagrange', 'lagrange', NULL, 'Copper', 'ship_asteroid', 17.8, 0.1, '4.x', 'hpp_lagrange_d'),
('Stanton', 'L4 Lagrange', 'lagrange', NULL, 'Ice', 'ship_asteroid', 17.8, 0.1, '4.x', 'hpp_lagrange_d'),
('Stanton', 'L4 Lagrange', 'lagrange', NULL, 'Iron', 'ship_asteroid', 17.9, 0.1, '4.x', 'hpp_lagrange_d'),
('Stanton', 'L4/L5 Lagrange', 'lagrange', NULL, 'Agricium', 'ship_asteroid', 28.5, 0.015625, '4.x', 'hpp_lagrange_g'),
('Stanton', 'L4/L5 Lagrange', 'lagrange', NULL, 'Beryl', 'ship_asteroid', 18.0, 0.015625, '4.x', 'hpp_lagrange_g'),
('Stanton', 'L4/L5 Lagrange', 'lagrange', NULL, 'Copper', 'ship_asteroid', 17.8, 0.015625, '4.x', 'hpp_lagrange_g'),
('Stanton', 'L4/L5 Lagrange', 'lagrange', NULL, 'Ice', 'ship_asteroid', 17.8, 0.015625, '4.x', 'hpp_lagrange_g'),
('Stanton', 'L4/L5 Lagrange', 'lagrange', NULL, 'Iron', 'ship_asteroid', 17.9, 0.015625, '4.x', 'hpp_lagrange_g'),
('Stanton', 'L5 Lagrange', 'lagrange', NULL, 'Bexalite', 'ship_asteroid', 18.0, 0.3, '4.x', 'hpp_lagrange_e'),
('Stanton', 'L5 Lagrange', 'lagrange', NULL, 'Copper', 'ship_asteroid', 17.8, 0.3, '4.x', 'hpp_lagrange_e'),
('Stanton', 'L5 Lagrange', 'lagrange', NULL, 'Ice', 'ship_asteroid', 17.8, 0.3, '4.x', 'hpp_lagrange_e'),
('Stanton', 'L5 Lagrange', 'lagrange', NULL, 'Iron', 'ship_asteroid', 17.9, 0.3, '4.x', 'hpp_lagrange_e'),
('Stanton', 'L5 Lagrange', 'lagrange', NULL, 'Titanium', 'ship_asteroid', 28.5, 0.3, '4.x', 'hpp_lagrange_e'),
('Stanton', 'Lyria', 'moon', 'ArcCorp', 'Aphorite', 'fps', 61.1, 25.0, '4.x', 'hpp_stanton3b'),
('Stanton', 'Lyria', 'moon', 'ArcCorp', 'Beradom', 'ground_vehicle', 56.0, 12.5, '4.x', 'hpp_stanton3b'),
('Stanton', 'Lyria', 'moon', 'ArcCorp', 'Beryl', 'ship_asteroid', 18.0, 6.0, '4.x', 'hpp_stanton3b'),
('Stanton', 'Lyria', 'moon', 'ArcCorp', 'Copper', 'ship_asteroid', 25.8, 6.0, '4.x', 'hpp_stanton3b'),
('Stanton', 'Lyria', 'moon', 'ArcCorp', 'Dolivine', 'fps', 36.9, 25.0, '4.x', 'hpp_stanton3b'),
('Stanton', 'Lyria', 'moon', 'ArcCorp', 'Feynmaline', 'ground_vehicle', 4.0, 12.5, '4.x', 'hpp_stanton3b'),
('Stanton', 'Lyria', 'moon', 'ArcCorp', 'Glacosite', 'ground_vehicle', 40.0, 12.5, '4.x', 'hpp_stanton3b'),
('Stanton', 'Lyria', 'moon', 'ArcCorp', 'Iron', 'ship_asteroid', 25.7, 6.0, '4.x', 'hpp_stanton3b'),
('Stanton', 'Lyria', 'moon', 'ArcCorp', 'Janalite', 'fps', 2.0, 25.0, '4.x', 'hpp_stanton3b'),
('Stanton', 'Lyria', 'moon', 'ArcCorp', 'Laranite', 'ship_asteroid', 28.5, 6.0, '4.x', 'hpp_stanton3b'),
('Stanton', 'Lyria', 'moon', 'ArcCorp', 'Quantainium', 'ship_asteroid', 2.0, 6.0, '4.x', 'hpp_stanton3b'),
('Stanton', 'MicroTech', 'planet', NULL, 'Aphorite', 'fps', 61.1, 25.0, '4.x', 'hpp_stanton4, hpp_stanton4a'),
('Stanton', 'MicroTech', 'planet', NULL, 'Beradom', 'ground_vehicle', 28.0, 12.5, '4.x', 'hpp_stanton4, hpp_stanton4a'),
('Stanton', 'MicroTech', 'planet', NULL, 'Dolivine', 'fps', 36.9, 25.0, '4.x', 'hpp_stanton4, hpp_stanton4a'),
('Stanton', 'MicroTech', 'planet', NULL, 'Feynmaline', 'ground_vehicle', 4.0, 12.5, '4.x', 'hpp_stanton4, hpp_stanton4a'),
('Stanton', 'MicroTech', 'planet', NULL, 'Glacosite', 'ground_vehicle', 68.0, 12.5, '4.x', 'hpp_stanton4, hpp_stanton4a'),
('Stanton', 'MicroTech', 'planet', NULL, 'Gold', 'unknown', 24.69, 35.0, '4.x', 'hpp_stanton4'),
('Stanton', 'MicroTech', 'planet', NULL, 'Hephaestanite', 'ship_asteroid', 32.7, 6.0, '4.x', 'hpp_stanton4, hpp_stanton4a'),
('Stanton', 'MicroTech', 'planet', NULL, 'Ice', 'ship_asteroid', 32.7, 6.0, '4.x', 'hpp_stanton4, hpp_stanton4a'),
('Stanton', 'MicroTech', 'planet', NULL, 'Iron', 'ship_asteroid', 32.6, 6.0, '4.x', 'hpp_stanton4, hpp_stanton4a'),
('Stanton', 'MicroTech', 'planet', NULL, 'Janalite', 'fps', 2.0, 25.0, '4.x', 'hpp_stanton4, hpp_stanton4a'),
('Stanton', 'MicroTech', 'planet', NULL, 'Quantainium', 'ship_asteroid', 2.0, 6.0, '4.x', 'hpp_stanton4, hpp_stanton4a'),
('Pyro', 'Monox', 'planet', NULL, 'Aphorite', 'fps', 58.6, 12.5, '4.x', 'hpp_pyro2'),
('Pyro', 'Monox', 'planet', NULL, 'Dolivine', 'fps', 35.4, 12.5, '4.x', 'hpp_pyro2'),
('Pyro', 'Monox', 'planet', NULL, 'Glacosite', 'ground_vehicle', 100.0, 25.0, '4.x', 'hpp_pyro2'),
('Pyro', 'Monox', 'planet', NULL, 'Hadanite', 'fps', 6.0, 12.5, '4.x', 'hpp_pyro2'),
('Pyro', 'Monox', 'planet', NULL, 'Hephaestanite', 'ship_asteroid', 32.73, 7.5, '4.x', 'hpp_pyro2'),
('Pyro', 'Monox', 'planet', NULL, 'Iron', 'ship_asteroid', 32.63, 7.5, '4.x', 'hpp_pyro2'),
('Pyro', 'Monox', 'planet', NULL, 'Stileron', 'ship_asteroid', 2.0, 7.5, '4.x', 'hpp_pyro2'),
('Pyro', 'Monox', 'planet', NULL, 'Tin', 'ship_asteroid', 32.63, 7.5, '4.x', 'hpp_pyro2'),
('Pyro', 'Pyro I', 'planet', NULL, 'Aphorite', 'fps', 58.6, 12.5, '4.x', 'hpp_pyro1'),
('Pyro', 'Pyro I', 'planet', NULL, 'Beradom', 'ground_vehicle', 100.0, 25.0, '4.x', 'hpp_pyro1'),
('Pyro', 'Pyro I', 'planet', NULL, 'Copper', 'ship_asteroid', 32.63, 7.5, '4.x', 'hpp_pyro1'),
('Pyro', 'Pyro I', 'planet', NULL, 'Dolivine', 'fps', 35.4, 12.5, '4.x', 'hpp_pyro1'),
('Pyro', 'Pyro I', 'planet', NULL, 'Hadanite', 'fps', 6.0, 12.5, '4.x', 'hpp_pyro1'),
('Pyro', 'Pyro I', 'planet', NULL, 'Iron', 'ship_asteroid', 32.73, 7.5, '4.x', 'hpp_pyro1'),
('Pyro', 'Pyro I', 'planet', NULL, 'Stileron', 'ship_asteroid', 2.0, 7.5, '4.x', 'hpp_pyro1'),
('Pyro', 'Pyro I', 'planet', NULL, 'Tin', 'ship_asteroid', 32.63, 7.5, '4.x', 'hpp_pyro1'),
('Pyro', 'Pyro III', 'planet', NULL, 'Aphorite', 'fps', 61.1, 12.5, '4.x', 'hpp_pyro3'),
('Pyro', 'Pyro III', 'planet', NULL, 'Beradom', 'ground_vehicle', 100.0, 25.0, '4.x', 'hpp_pyro3'),
('Pyro', 'Pyro III', 'planet', NULL, 'Borase', 'ship_asteroid', 18.0, 7.5, '4.x', 'hpp_pyro3'),
('Pyro', 'Pyro III', 'planet', NULL, 'Dolivine', 'fps', 36.9, 12.5, '4.x', 'hpp_pyro3'),
('Pyro', 'Pyro III', 'planet', NULL, 'Iron', 'ship_asteroid', 35.0, 7.5, '4.x', 'hpp_pyro3'),
('Pyro', 'Pyro III', 'planet', NULL, 'Janalite', 'fps', 2.0, 12.5, '4.x', 'hpp_pyro3'),
('Pyro', 'Pyro III', 'planet', NULL, 'Quartz', 'ship_asteroid', 35.0, 7.5, '4.x', 'hpp_pyro3'),
('Pyro', 'Pyro III', 'planet', NULL, 'Riccite', 'ship_asteroid', 10.0, 7.5, '4.x', 'hpp_pyro3'),
('Pyro', 'Pyro III', 'planet', NULL, 'Stileron', 'ship_asteroid', 2.0, 7.5, '4.x', 'hpp_pyro3'),
('Pyro', 'Pyro V', 'planet', NULL, 'Aphorite', 'fps', 58.6, 12.5, '4.x', 'hpp_pyro5a'),
('Pyro', 'Pyro V', 'planet', NULL, 'Dolivine', 'fps', 35.4, 12.5, '4.x', 'hpp_pyro5a'),
('Pyro', 'Pyro V', 'planet', NULL, 'Feynmaline', 'ground_vehicle', 100.0, 25.0, '4.x', 'hpp_pyro5a'),
('Pyro', 'Pyro V', 'planet', NULL, 'Gold', 'ship_asteroid', 18.0, 7.5, '4.x', 'hpp_pyro5a'),
('Pyro', 'Pyro V', 'planet', NULL, 'Hadanite', 'fps', 6.0, 12.5, '4.x', 'hpp_pyro5a'),
('Pyro', 'Pyro V', 'planet', NULL, 'Riccite', 'ship_asteroid', 10.0, 7.5, '4.x', 'hpp_pyro5a'),
('Pyro', 'Pyro V', 'planet', NULL, 'Silicon', 'ship_asteroid', 36.0, 7.5, '4.x', 'hpp_pyro5a'),
('Pyro', 'Pyro V', 'planet', NULL, 'Tin', 'ship_asteroid', 36.0, 7.5, '4.x', 'hpp_pyro5a'),
('Pyro', 'Pyro V-b', 'moon', NULL, 'Aphorite', 'fps', 58.6, 12.5, '4.x', 'hpp_pyro5b'),
('Pyro', 'Pyro V-b', 'moon', NULL, 'Beradom', 'ground_vehicle', 50.0, 25.0, '4.x', 'hpp_pyro5b'),
('Pyro', 'Pyro V-b', 'moon', NULL, 'Dolivine', 'fps', 35.4, 12.5, '4.x', 'hpp_pyro5b'),
('Pyro', 'Pyro V-b', 'moon', NULL, 'Glacosite', 'ground_vehicle', 50.0, 25.0, '4.x', 'hpp_pyro5b'),
('Pyro', 'Pyro V-b', 'moon', NULL, 'Gold', 'ship_asteroid', 18.0, 7.5, '4.x', 'hpp_pyro5b'),
('Pyro', 'Pyro V-b', 'moon', NULL, 'Hadanite', 'fps', 6.0, 12.5, '4.x', 'hpp_pyro5b'),
('Pyro', 'Pyro V-b', 'moon', NULL, 'Iron', 'ship_asteroid', 36.0, 7.5, '4.x', 'hpp_pyro5b'),
('Pyro', 'Pyro V-b', 'moon', NULL, 'Riccite', 'ship_asteroid', 10.0, 7.5, '4.x', 'hpp_pyro5b'),
('Pyro', 'Pyro V-b', 'moon', NULL, 'Silicon', 'ship_asteroid', 36.0, 7.5, '4.x', 'hpp_pyro5b'),
('Pyro', 'Pyro V-c', 'moon', NULL, 'Aphorite', 'fps', 58.6, 12.5, '4.x', 'hpp_pyro5c'),
('Pyro', 'Pyro V-c', 'moon', NULL, 'Borase', 'ship_asteroid', 18.0, 7.5, '4.x', 'hpp_pyro5c'),
('Pyro', 'Pyro V-c', 'moon', NULL, 'Dolivine', 'fps', 35.4, 12.5, '4.x', 'hpp_pyro5c'),
('Pyro', 'Pyro V-c', 'moon', NULL, 'Glacosite', 'ground_vehicle', 100.0, 25.0, '4.x', 'hpp_pyro5c'),
('Pyro', 'Pyro V-c', 'moon', NULL, 'Hadanite', 'fps', 6.0, 12.5, '4.x', 'hpp_pyro5c'),
('Pyro', 'Pyro V-c', 'moon', NULL, 'Iron', 'ship_asteroid', 43.5, 7.5, '4.x', 'hpp_pyro5c'),
('Pyro', 'Pyro V-c', 'moon', NULL, 'Riccite', 'ship_asteroid', 10.0, 7.5, '4.x', 'hpp_pyro5c'),
('Pyro', 'Pyro V-c', 'moon', NULL, 'Tungsten', 'ship_asteroid', 28.5, 7.5, '4.x', 'hpp_pyro5c'),
('Pyro', 'Pyro V-d', 'moon', NULL, 'Aphorite', 'fps', 58.6, 12.5, '4.x', 'hpp_pyro5d'),
('Pyro', 'Pyro V-d', 'moon', NULL, 'Beradom', 'ground_vehicle', 100.0, 25.0, '4.x', 'hpp_pyro5d'),
('Pyro', 'Pyro V-d', 'moon', NULL, 'Bexalite', 'ship_asteroid', 9.0, 7.5, '4.x', 'hpp_pyro5d'),
('Pyro', 'Pyro V-d', 'moon', NULL, 'Dolivine', 'fps', 35.4, 12.5, '4.x', 'hpp_pyro5d'),
('Pyro', 'Pyro V-d', 'moon', NULL, 'Gold', 'ship_asteroid', 9.0, 7.5, '4.x', 'hpp_pyro5d'),
('Pyro', 'Pyro V-d', 'moon', NULL, 'Hadanite', 'fps', 6.0, 12.5, '4.x', 'hpp_pyro5d'),
('Pyro', 'Pyro V-d', 'moon', NULL, 'Iron', 'ship_asteroid', 26.7, 7.5, '4.x', 'hpp_pyro5d'),
('Pyro', 'Pyro V-d', 'moon', NULL, 'Silicon', 'ship_asteroid', 26.8, 7.5, '4.x', 'hpp_pyro5d'),
('Pyro', 'Pyro V-d', 'moon', NULL, 'Tungsten', 'ship_asteroid', 28.5, 7.5, '4.x', 'hpp_pyro5d'),
('Pyro', 'Pyro V-e', 'moon', NULL, 'Aphorite', 'fps', 61.1, 12.5, '4.x', 'hpp_pyro5e'),
('Pyro', 'Pyro V-e', 'moon', NULL, 'Aslarite', 'ship_asteroid', 28.5, 7.5, '4.x', 'hpp_pyro5e'),
('Pyro', 'Pyro V-e', 'moon', NULL, 'Bexalite', 'ship_asteroid', 9.0, 7.5, '4.x', 'hpp_pyro5e'),
('Pyro', 'Pyro V-e', 'moon', NULL, 'Borase', 'ship_asteroid', 9.0, 7.5, '4.x', 'hpp_pyro5e'),
('Pyro', 'Pyro V-e', 'moon', NULL, 'Dolivine', 'fps', 36.9, 12.5, '4.x', 'hpp_pyro5e'),
('Pyro', 'Pyro V-e', 'moon', NULL, 'Feynmaline', 'ground_vehicle', 100.0, 25.0, '4.x', 'hpp_pyro5e'),
('Pyro', 'Pyro V-e', 'moon', NULL, 'Hephaestanite', 'ship_asteroid', 26.7, 7.5, '4.x', 'hpp_pyro5e'),
('Pyro', 'Pyro V-e', 'moon', NULL, 'Iron', 'ship_asteroid', 26.8, 7.5, '4.x', 'hpp_pyro5e'),
('Pyro', 'Pyro V-e', 'moon', NULL, 'Janalite', 'fps', 2.0, 12.5, '4.x', 'hpp_pyro5e'),
('Pyro', 'Pyro V-f', 'moon', NULL, 'Agricium', 'ship_asteroid', 14.2, 7.5, '4.x', 'hpp_pyro5f'),
('Pyro', 'Pyro V-f', 'moon', NULL, 'Aphorite', 'fps', 58.6, 12.5, '4.x', 'hpp_pyro5f'),
('Pyro', 'Pyro V-f', 'moon', NULL, 'Aslarite', 'ship_asteroid', 14.2, 7.5, '4.x', 'hpp_pyro5f'),
('Pyro', 'Pyro V-f', 'moon', NULL, 'Bexalite', 'ship_asteroid', 18.0, 7.5, '4.x', 'hpp_pyro5f'),
('Pyro', 'Pyro V-f', 'moon', NULL, 'Dolivine', 'fps', 35.4, 12.5, '4.x', 'hpp_pyro5f'),
('Pyro', 'Pyro V-f', 'moon', NULL, 'Glacosite', 'ground_vehicle', 100.0, 25.0, '4.x', 'hpp_pyro5f'),
('Pyro', 'Pyro V-f', 'moon', NULL, 'Hadanite', 'fps', 6.0, 12.5, '4.x', 'hpp_pyro5f'),
('Pyro', 'Pyro V-f', 'moon', NULL, 'Hephaestanite', 'ship_asteroid', 26.8, 7.5, '4.x', 'hpp_pyro5f'),
('Pyro', 'Pyro V-f', 'moon', NULL, 'Iron', 'ship_asteroid', 26.8, 7.5, '4.x', 'hpp_pyro5f'),
('Pyro', 'Pyro VI', 'planet', NULL, 'Agricium', 'ship_asteroid', 14.2, 7.5, '4.x', 'hpp_pyro6'),
('Pyro', 'Pyro VI', 'planet', NULL, 'Aphorite', 'fps', 61.1, 12.5, '4.x', 'hpp_pyro6'),
('Pyro', 'Pyro VI', 'planet', NULL, 'Copper', 'ship_asteroid', 20.8, 7.5, '4.x', 'hpp_pyro6'),
('Pyro', 'Pyro VI', 'planet', NULL, 'Dolivine', 'fps', 36.9, 12.5, '4.x', 'hpp_pyro6'),
('Pyro', 'Pyro VI', 'planet', NULL, 'Feynmaline', 'ground_vehicle', 100.0, 25.0, '4.x', 'hpp_pyro6'),
('Pyro', 'Pyro VI', 'planet', NULL, 'Gold', 'ship_asteroid', 18.0, 7.5, '4.x', 'hpp_pyro6'),
('Pyro', 'Pyro VI', 'planet', NULL, 'Ice', 'ship_asteroid', 20.8, 7.5, '4.x', 'hpp_pyro6'),
('Pyro', 'Pyro VI', 'planet', NULL, 'Janalite', 'fps', 2.0, 12.5, '4.x', 'hpp_pyro6'),
('Pyro', 'Pyro VI', 'planet', NULL, 'Riccite', 'ship_asteroid', 10.0, 7.5, '4.x', 'hpp_pyro6'),
('Pyro', 'Pyro VI', 'planet', NULL, 'Stileron', 'ship_asteroid', 2.0, 7.5, '4.x', 'hpp_pyro6'),
('Pyro', 'Pyro VI', 'planet', NULL, 'Titanium', 'ship_asteroid', 14.2, 7.5, '4.x', 'hpp_pyro6'),
('Stanton', 'Yela', 'moon', 'Crusader', 'Agricium', 'ship_asteroid', 28.5, 6.0, '4.x', 'hpp_stanton2c'),
('Stanton', 'Yela', 'moon', 'Crusader', 'Aphorite', 'fps', 58.6, 25.0, '4.x', 'hpp_stanton2c'),
('Stanton', 'Yela', 'moon', 'Crusader', 'Beradom', 'ground_vehicle', 24.0, 12.5, '4.x', 'hpp_stanton2c'),
('Stanton', 'Yela', 'moon', 'Crusader', 'Dolivine', 'fps', 35.4, 25.0, '4.x', 'hpp_stanton2c'),
('Stanton', 'Yela', 'moon', 'Crusader', 'Feynmaline', 'ground_vehicle', 8.0, 12.5, '4.x', 'hpp_stanton2c'),
('Stanton', 'Yela', 'moon', 'Crusader', 'Glacosite', 'ground_vehicle', 68.0, 12.5, '4.x', 'hpp_stanton2c'),
('Stanton', 'Yela', 'moon', 'Crusader', 'Hadanite', 'fps', 6.0, 25.0, '4.x', 'hpp_stanton2c'),
('Stanton', 'Yela', 'moon', 'Crusader', 'Quantainium', 'ship_asteroid', 2.0, 6.0, '4.x', 'hpp_stanton2c'),
('Stanton', 'Yela', 'moon', 'Crusader', 'Quartz', 'ship_asteroid', 25.7, 6.0, '4.x', 'hpp_stanton2c'),
('Stanton', 'Yela', 'moon', 'Crusader', 'Silicon', 'ship_asteroid', 25.8, 6.0, '4.x', 'hpp_stanton2c'),
('Stanton', 'Yela', 'moon', 'Crusader', 'Taranite', 'ship_asteroid', 18.0, 6.0, '4.x', 'hpp_stanton2c'),
('Stanton', 'Yela Belt', 'asteroid_belt', NULL, 'Copper', 'ship_asteroid', 20.5, 0.2, '4.x', 'hpp_stanton2c_belt'),
('Stanton', 'Yela Belt', 'asteroid_belt', NULL, 'Ice', 'ship_asteroid', 20.5, 0.2, '4.x', 'hpp_stanton2c_belt'),
('Stanton', 'Yela Belt', 'asteroid_belt', NULL, 'Iron', 'ship_asteroid', 20.5, 0.2, '4.x', 'hpp_stanton2c_belt'),
('Stanton', 'Yela Belt', 'asteroid_belt', NULL, 'Ouratite', 'ship_asteroid', 10.0, 0.2, '4.x', 'hpp_stanton2c_belt'),
('Stanton', 'Yela Belt', 'asteroid_belt', NULL, 'Titanium', 'ship_asteroid', 28.5, 0.2, '4.x', 'hpp_stanton2c_belt'),
('Stanton', 'hpp_lagrange_occupied', 'unknown', NULL, 'Agricium', 'ship_asteroid', 28.5, 0.009375, '4.x', 'hpp_lagrange_occupied'),
('Stanton', 'hpp_lagrange_occupied', 'unknown', NULL, 'Beryl', 'ship_asteroid', 18.0, 0.009375, '4.x', 'hpp_lagrange_occupied'),
('Stanton', 'hpp_lagrange_occupied', 'unknown', NULL, 'Copper', 'ship_asteroid', 17.8, 0.009375, '4.x', 'hpp_lagrange_occupied'),
('Stanton', 'hpp_lagrange_occupied', 'unknown', NULL, 'Ice', 'ship_asteroid', 17.8, 0.009375, '4.x', 'hpp_lagrange_occupied'),
('Stanton', 'hpp_lagrange_occupied', 'unknown', NULL, 'Iron', 'ship_asteroid', 17.9, 0.009375, '4.x', 'hpp_lagrange_occupied'),
('Pyro', 'hpp_pyro_akirocluster', 'unknown', NULL, 'Copper', 'ship_asteroid', 14.9, 0.1, '4.x', 'hpp_pyro_akirocluster'),
('Pyro', 'hpp_pyro_akirocluster', 'unknown', NULL, 'Ice', 'ship_asteroid', 14.9, 0.1, '4.x', 'hpp_pyro_akirocluster'),
('Pyro', 'hpp_pyro_akirocluster', 'unknown', NULL, 'Iron', 'ship_asteroid', 14.8, 0.1, '4.x', 'hpp_pyro_akirocluster'),
('Pyro', 'hpp_pyro_akirocluster', 'unknown', NULL, 'Riccite', 'ship_asteroid', 10.0, 0.1, '4.x', 'hpp_pyro_akirocluster'),
('Pyro', 'hpp_pyro_akirocluster', 'unknown', NULL, 'Silicon', 'ship_asteroid', 14.9, 0.1, '4.x', 'hpp_pyro_akirocluster'),
('Pyro', 'hpp_pyro_akirocluster', 'unknown', NULL, 'Stileron', 'ship_asteroid', 2.0, 0.1, '4.x', 'hpp_pyro_akirocluster'),
('Pyro', 'hpp_pyro_akirocluster', 'unknown', NULL, 'Torite', 'ship_asteroid', 28.5, 0.1, '4.x', 'hpp_pyro_akirocluster'),
('Pyro', 'hpp_pyro_cool01', 'unknown', NULL, 'Borase', 'ship_asteroid', 18.0, 0.1, '4.x', 'hpp_pyro_cool01'),
('Pyro', 'hpp_pyro_cool01', 'unknown', NULL, 'Ice', 'ship_asteroid', 26.8, 0.1, '4.x', 'hpp_pyro_cool01'),
('Pyro', 'hpp_pyro_cool01', 'unknown', NULL, 'Silicon', 'ship_asteroid', 26.7, 0.1, '4.x', 'hpp_pyro_cool01'),
('Pyro', 'hpp_pyro_cool01', 'unknown', NULL, 'Titanium', 'ship_asteroid', 28.5, 0.1, '4.x', 'hpp_pyro_cool01'),
('Pyro', 'hpp_pyro_cool02', 'unknown', NULL, 'Aslarite', 'ship_asteroid', 28.5, 0.1, '4.x', 'hpp_pyro_cool02'),
('Pyro', 'hpp_pyro_cool02', 'unknown', NULL, 'Ice', 'ship_asteroid', 26.8, 0.1, '4.x', 'hpp_pyro_cool02'),
('Pyro', 'hpp_pyro_cool02', 'unknown', NULL, 'Silicon', 'ship_asteroid', 26.7, 0.1, '4.x', 'hpp_pyro_cool02'),
('Pyro', 'hpp_pyro_cool02', 'unknown', NULL, 'Taranite', 'ship_asteroid', 18.0, 0.1, '4.x', 'hpp_pyro_cool02'),
('Pyro', 'hpp_pyro_deepspaceasteroids', 'unknown', NULL, 'Aluminium', 'ship_asteroid', 14.9, 0.1, '4.x', 'hpp_pyro_deepspaceasteroids'),
('Pyro', 'hpp_pyro_deepspaceasteroids', 'unknown', NULL, 'Corundum', 'ship_asteroid', 14.9, 0.1, '4.x', 'hpp_pyro_deepspaceasteroids'),
('Pyro', 'hpp_pyro_deepspaceasteroids', 'unknown', NULL, 'Quartz', 'ship_asteroid', 14.9, 0.1, '4.x', 'hpp_pyro_deepspaceasteroids'),
('Pyro', 'hpp_pyro_deepspaceasteroids', 'unknown', NULL, 'Riccite', 'ship_asteroid', 10.0, 0.1, '4.x', 'hpp_pyro_deepspaceasteroids'),
('Pyro', 'hpp_pyro_deepspaceasteroids', 'unknown', NULL, 'Stileron', 'ship_asteroid', 2.0, 0.1, '4.x', 'hpp_pyro_deepspaceasteroids'),
('Pyro', 'hpp_pyro_deepspaceasteroids', 'unknown', NULL, 'Tin', 'ship_asteroid', 14.8, 0.1, '4.x', 'hpp_pyro_deepspaceasteroids'),
('Pyro', 'hpp_pyro_deepspaceasteroids', 'unknown', NULL, 'Torite', 'ship_asteroid', 28.5, 0.1, '4.x', 'hpp_pyro_deepspaceasteroids'),
('Pyro', 'hpp_pyro_warm01', 'unknown', NULL, 'Agricium', 'ship_asteroid', 28.5, 0.1, '4.x', 'hpp_pyro_warm01'),
('Pyro', 'hpp_pyro_warm01', 'unknown', NULL, 'Bexalite', 'ship_asteroid', 18.0, 0.1, '4.x', 'hpp_pyro_warm01'),
('Pyro', 'hpp_pyro_warm01', 'unknown', NULL, 'Copper', 'ship_asteroid', 26.7, 0.1, '4.x', 'hpp_pyro_warm01'),
('Pyro', 'hpp_pyro_warm01', 'unknown', NULL, 'Iron', 'ship_asteroid', 26.8, 0.1, '4.x', 'hpp_pyro_warm01'),
('Pyro', 'hpp_pyro_warm02', 'unknown', NULL, 'Copper', 'ship_asteroid', 26.7, 0.1, '4.x', 'hpp_pyro_warm02'),
('Pyro', 'hpp_pyro_warm02', 'unknown', NULL, 'Gold', 'ship_asteroid', 18.0, 0.1, '4.x', 'hpp_pyro_warm02'),
('Pyro', 'hpp_pyro_warm02', 'unknown', NULL, 'Iron', 'ship_asteroid', 26.8, 0.1, '4.x', 'hpp_pyro_warm02'),
('Pyro', 'hpp_pyro_warm02', 'unknown', NULL, 'Tungsten', 'ship_asteroid', 28.5, 0.1, '4.x', 'hpp_pyro_warm02'),
('Stanton', 'hpp_resourcerush_gold', 'unknown', NULL, 'Gold', 'ship_asteroid', 100.0, 0.5, '4.x', 'hpp_resourcerush_gold'),
('Stanton', 'hpp_resourcerush_gold_highdensity', 'unknown', NULL, 'Gold', 'ship_asteroid', 100.0, 5.0, '4.x', 'hpp_resourcerush_gold_highdensity');

CREATE INDEX idx_mineral_spawns_body ON mineral_spawns (system, body);
CREATE INDEX idx_mineral_spawns_mineral ON mineral_spawns (mineral);
CREATE INDEX idx_mineral_spawns_mining_type ON mineral_spawns (mining_type);